kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{OPENSHIFT_APP_NAME}}
  labels:
    app: {{OPENSHIFT_APP_NAME}}
    app.kubernetes.io/part-of: {{OPENSHIFT_APP_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{OPENSHIFT_APP_NAME}}
  template:
    metadata:
      labels:
        app: {{OPENSHIFT_APP_NAME}}
    spec:
      containers:
        - name: {{OPENSHIFT_APP_NAME}}
          resources: {}
          ports:
            - containerPort: 8080
              protocol: TCP
          image: ghcr.io/{{IMAGE_OWNER}}/{{IMAGE_NAME}}:{{IMAGE_TAG}}
          imagePullPolicy: Always