kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{OPENSHIFT_APP_NAME}}
  labels:
    app: {{OPENSHIFT_APP_NAME}}
    app.kubernetes.io/part-of: {{OPENSHIFT_APP_NAME}}
spec:
  to:
    kind: Service
    name: {{OPENSHIFT_APP_NAME}}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect