kind: Service
apiVersion: v1
metadata:
  name: {{OPENSHIFT_APP_NAME}}
  labels:
    app: {{OPENSHIFT_APP_NAME}}
    app.kubernetes.io/part-of: {{OPENSHIFT_APP_NAME}}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{OPENSHIFT_APP_NAME}}