name: OpenShift Deploy

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/html-openshift-app:${{ github.ref_name }}
      IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME

      - name: Replace image tag in deployment.yaml
        run: |
          sed -i 's|{{IMAGE_TAG}}|${{ github.ref_name }}|g' deployment.yaml
          sed -i 's|{{IMAGE_OWNER}}|${{ github.repository_owner }}|g' deployment.yaml

      - name: Install OpenShift CLI
        run: |
          curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz -o oc.tar.gz
          tar -xzf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Log in to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify=true
          oc project 254501-heloli

      - name: Apply deployment
        run: |
          oc apply -f deployment.yaml
